# Generated by Django 4.2 on 2023-07-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.JSONField()),
                ('person_id_new', models.JSONField()),
                ('person', models.JSONField()),
                ('person_new', models.JSONField()),
                ('interests', models.JSONField()),
                ('interests_new', models.JSONField()),
                ('institutes', models.JSONField()),
                ('institutes_new', models.JSONField()),
                ('faculties', models.JSONField()),
                ('faculties_new', models.JSONField()),
                ('departments', models.JSONField()),
                ('departments_new', models.JSONField()),
                ('advisors', models.JSONField()),
                ('advisors_new', models.JSONField()),
                ('roles', models.JSONField()),
                ('roles_new', models.JSONField()),
                ('offered', models.JSONField()),
                ('offered_new', models.JSONField()),
                ('wanted', models.JSONField()),
                ('wanted_new', models.JSONField()),
            ],
        ),
    ]
