# Generated by Django 4.2 on 2023-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsubmission',
            name='advisors',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='advisors_new',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='departments',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='departments_new',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='faculties',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='faculties_new',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='institutes',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='institutes_new',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='interests',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='interests_new',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='offered',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='offered_new',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_id',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_id_new',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_new',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='roles',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='roles_new',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='wanted',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='wanted_new',
            field=models.JSONField(null=True),
        ),
    ]
