# Generated by Django 4.2 on 2023-07-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0002_alter_editsubmission_advisors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsubmission',
            name='person_id',
            field=models.JSONField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_id_new',
            field=models.JSONField(null=True, unique=True),
        ),
    ]
