# Generated by Django 4.2 on 2023-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0003_alter_editsubmission_person_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editsubmission',
            name='person',
        ),
        migrations.RemoveField(
            model_name='editsubmission',
            name='person_new',
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='person_email',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='person_email_new',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='person_name',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='person_name_new',
            field=models.JSONField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='person_title',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='editsubmission',
            name='person_title_new',
            field=models.JSONField(null=True),
        ),
    ]
