# Generated by Django 4.2 on 2023-07-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0004_remove_editsubmission_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsubmission',
            name='person_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_email_new',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_id_new',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_name_new',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_title_new',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
