# Generated by Django 4.2 on 2023-07-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0005_alter_editsubmission_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsubmission',
            name='person_email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_email_new',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_name',
            field=models.CharField(default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_name_new',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
