# Generated by Django 4.2 on 2023-07-28 13:40

from django.db import migrations, models
import expertise.models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0006_alter_editsubmission_person_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsubmission',
            name='advisors',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='advisors_new',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='departments',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='departments_new',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='faculties',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='faculties_new',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='institutes',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='institutes_new',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='interests',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='interests_new',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='offered',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='offered_new',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_title',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='person_title_new',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='roles',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='roles_new',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='wanted',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
        migrations.AlterField(
            model_name='editsubmission',
            name='wanted_new',
            field=models.JSONField(default=expertise.models.default_list, null=True),
        ),
    ]
