# Generated by Django 4.2 on 2023-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0007_alter_editsubmission_advisors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsubmission',
            name='person_email_new',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
    ]
