# Generated by Django 4.2 on 2023-07-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0008_alter_editsubmission_person_email_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editsubmission',
            name='person_email_new',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
