# Generated by Django 4.2 on 2023-09-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0011_shareparameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareparameters',
            name='parameters',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
