# Generated by Django 4.2 on 2023-10-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0012_alter_shareparameters_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='editsubmission',
            name='action',
            field=models.CharField(choices=[('edit', 'edit'), ('delete', 'delete')], default='edit', max_length=30),
            preserve_default=False,
        ),
    ]
